### ISSUE TITLE
Add a UUID type

### ISSUE THREAD

**Issue by the-other-tim-brown** [apache/incubator-xtable#112]
Create a UUID type in OneType and handle it appropriately in all converters. Only Iceberg has a concept of a UUID and it is a fixed size byte array in the underlying parquet files. We should aim to preserve the metadata that this byte array came from a UUID for round trip conversions.

**Comment by yyy1000** [comment]
I'm new to this project and want to begin contribute with this:)

**Comment by the-other-tim-brown** [comment]
@yyy1000 welcome! Feel free to assign it to yourself when you begin working on it.

**Comment by yyy1000** [comment]
/assign
How can I assign it to me?

**Comment by the-other-tim-brown** [comment]
> /assign How can I assign it to myself? :)

I've assigned it to you. It may be a github permissions issue and only repo owners can assign. In the top right there is assignees if you are not familiar with the GitHub UI for issues. 
<img width="349" alt="image" src="https://github.com/onetable-io/onetable/assets/1360517/16ea0a0f-451e-44cd-9f55-2f518a5cd73c">

**Comment by genzarchitect** [comment]
is this issue resolved ?
Could you assign it to me ?

**Comment by the-other-tim-brown** [comment]
@genzarchitect  this is not resolved but there is an open PR. @yyy1000 are you still working on this?

**Comment by yyy1000** [comment]
@the-other-tim-brown Sorry about that, I became busy these days so I can't work on this. :(

**Comment by the-other-tim-brown** [comment]
@yyy1000 no worries. Feel free to reach out when you are less busy if you want to work on any other features.

@genzarchitect I've reassigned this to you. Take a look at https://github.com/onetable-io/onetable/pull/267 for the progress that was already made on the task.

**Comment by danielhumanmod** [comment]
@the-other-tim-brown I noticed this issue has been open for more than 6 months, and I was wondering if I could help by working on it if @genzarchitect is busy currently?

**Comment by the-other-tim-brown** [comment]
@danielhumanmod, yes feel free to assign it to yourself and let me know if you need any help getting setup or making the changes.

**Comment by danielhumanmod** [comment]
Thanks, @the-other-tim-brown . I’ve submitted an initial PR (#518) to address this issue. However, I’ve also left some comments in the PR as questions regarding the Hudi converter. I would greatly appreciate it if you could take a look and help me with those.

BTW, would you mind helping to assign this issue to me? It seems I don’t have the permissions. XD
