### ISSUE TITLE
Fix Issues Raised by Dependabot

### ISSUE THREAD

**Issue by the-other-tim-brown** [apache/incubator-xtable#213]
Fix the issues raised by dependabot vulnerability alerts

**Comment by the-other-tim-brown** [comment]
There is one remaining issue around spark version that will be tackled next

**Comment by abhioncbr** [comment]
Hi, if this is still the issue, please assign it to me. I would like to give ut a try. Thanks

**Comment by the-other-tim-brown** [comment]
@abhioncbr the issue with spark version is already resolved. Marking this as closed.
