### ISSUE TITLE
Links in the new website still referencing onetable.dev

### ISSUE THREAD

**Issue by jcamachor** [apache/incubator-xtable#377]
For instance, the links at the top of the website (Docs, Blogs) are still referencing the old site.

Related to #352 

Cc @kywe665

**Comment by kywe665** [comment]
I'll fix this. I had assumption first PR would rename in place and 2nd would move the site domains. Should I open PR on this repo or in the new "-site" repo referenced here?: https://github.com/apache/incubator-xtable/issues/375

**Comment by jcamachor** [comment]
All the changes go against this repo for the time being, then after site is generated, I'll push it to the '-site' repo (this second part will need to be done manually until we fix #375)

**Comment by jcamachor** [comment]
Fixed in #378, thanks @kywe665 !
