### ISSUE TITLE
Capture all XTable Metadata in a JSON object

### ISSUE THREAD

**Issue by the-other-tim-brown** [apache/incubator-xtable#412]
Currently we add two entries to the metadata of the target tables. If we want to add more information, we'll need to add additional fields with this approach.

Instead, I am proposing we capture the metadata in a json object and only add a single entry to the metadata of the target tables. This json object can contain a version as well allowing for evolution of this metadata in the future.

**Comment by vinishjail97** [comment]
@the-other-tim-brown Can we close this issue ?
