### ISSUE TITLE
Maven Build Failure

### ISSUE THREAD

**Issue by BrennaBuuckMinio** [apache/incubator-xtable#413]
I ran `cd .. && mvn install -am -pl core -DskipTests -T 2` in the demo directory. I got this this error:

[INFO] --- spotless:2.43.0:check (default) @ xtable ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for xtable 0.1.0-SNAPSHOT:
[INFO] 
[INFO] xtable ............................................. FAILURE [  0.464 s]
[INFO] api ................................................ SKIPPED
[INFO] hudi-support ....................................... SKIPPED
[INFO] hudi-utils ......................................... SKIPPED
[INFO] core ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.508 s (Wall Clock)
[INFO] Finished at: 2024-04-10T11:06:53-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default) on project xtable: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check failed: You are running Spotless on JVM 21. This requires google-java-format of at least 1.17.0 (you are using 1.8).`

I'm sure it has something to do with my java environment, but I'm not sure how to resolve.

**Comment by the-other-tim-brown** [comment]
@BrennaBuuckMinio can you use java 11?

**Comment by BrennaBuuckMinio** [comment]
Perfect! Thank you. Sorry for the confusion.

**Comment by pateash** [comment]
@BrennaBuuckMinio this can be closed, I am not mistaken.
