### ISSUE TITLE
Optimize the module structure of the xtable

### ISSUE THREAD

**Issue by daragu** [apache/incubator-xtable#435]
### Feature Request / Improvement

Optimize the module structure of the xtable
- add same prefix to sub modules
- let the folder name of the module to match the artifactId

Changes
- api -> xtable-api
- core -> xtable-core
- hudi-support -> xtable-hudi-support
- utilities -> xtable-utilities
- website -> xtable-website

![图片](https://github.com/apache/incubator-xtable/assets/168054694/b1ebeeb2-c511-4d7b-af40-01064a4e612f)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daragu** [comment]
hi @the-other-tim-brown @vinishjail97,  what do you think?

https://github.com/daragu/incubator-xtable/tree/module

**Comment by the-other-tim-brown** [comment]
What is the enhancement that comes with this? It feels a bit arbitrary.

**Comment by daragu** [comment]
> What is the enhancement that comes with this? It feels a bit arbitrary.


1. For mvn projects, add same prefix to sub modules is friendly for developers.
  - https://github.com/apache/flink
  - https://github.com/apache/hadoop
  - https://github.com/apache/hudi
  - https://github.com/apache/paimon
  - https://github.com/apache/zookeeper

<br>

2. For Xtable project

From the official docs, user will use `utilities/target/utilities-0.1.0-SNAPSHOT-bundled.jar` to convert data lake formats

```
java -jar utilities/target/utilities-0.1.0-SNAPSHOT-bundled.jar --datasetConfig my_config.yaml
```

The name `utilities-0.1.0-SNAPSHOT-bundled.jar` does not have recognizability. The new name `xtable-utilities/target/xtable-utilities-0.1.0-SNAPSHOT-bundled.jar` is more recognizable.

**Comment by the-other-tim-brown** [comment]
@daragu thanks for the references and explanation. The changes sound good to me. The only thing is that the `website` directory is not maven module. Should that just stay as `website` for now? It may be moved in the future when we rethink how to manage the docs.

**Comment by daragu** [comment]
OK, the website directory will stay as website in the pullrequest.
