### ISSUE TITLE
Azure CI pending

### ISSUE THREAD

**Issue by daragu** [apache/incubator-xtable#438]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

https://dev.azure.com/apache-xtable-ci-org/apache-xtable-ci/_build/results?buildId=969&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a
```
##[error]This request was automatically failed because there were no enabled agents online to process the request for more than 7 days.
```

![图片](https://github.com/apache/incubator-xtable/assets/168054694/5f7955b7-0529-4a5d-8349-c87ff420d2f3)

### Are you willing to submit PR?

- [ ] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daragu** [comment]
hi @the-other-tim-brown, how about using github action?

**Comment by daragu** [comment]
Hi @the-other-tim-brown 
Recently, I have found that there are always problems with CI, and many CIs are in a pending state. I am familiar with GitHub Action and we can give it a try. I would be happy to hear your advice.

**Comment by vinishjail97** [comment]
@daragu There are some apache guidelines for using a azure CI pipeline, l will check more on this.

**Comment by daragu** [comment]
> @daragu There are some apache guidelines for using a azure CI pipeline, l will check more on this.

👍 thanks @vinishjail97.  But there is a limitation that forkers cannot trigger ci in their own warehouse with using Azure CI, 
https://github.com/daragu/incubator-xtable/actions/workflows/azure_ci_check.yml

**Comment by charlesy6** [comment]
+1, `Github Action` is better for developers.

**Comment by the-other-tim-brown** [comment]
@jcamachor what is your opinion on switching to GitHub actions?

**Comment by jcamachor** [comment]
@the-other-tim-brown , if I remember correctly, one of the reasons we were using Azure infrastructure before moving to the ASF was because the runners provided by the free GitHub plan were too slow or couldn't handle the tests at all. Do you recall? Also, do you know if the current ASF-provided runners will be sufficient for our needs?
I agree the current testing pipeline is a bit of a mess since Azure Pipelines necessary permissions don't mesh well with ASF, as described in https://issues.apache.org/jira/browse/INFRA-17030. This has led us to a somewhat makeshift solution (#363). It would be great to simplify things, and if GitHub-hosted runners for actions are viable, I'm +1. If we ever decide to use Azure infrastructure in the future for other types of tests, we can see how to run them on Azure at that time.

**Comment by daragu** [comment]
hi @the-other-tim-brown @jcamachor let's give it a try?

**Comment by the-other-tim-brown** [comment]
> @the-other-tim-brown , if I remember correctly, one of the reasons we were using Azure infrastructure before moving to the ASF was because the runners provided by the free GitHub plan were too slow or couldn't handle the tests at all. Do you recall? Also, do you know if the current ASF-provided runners will be sufficient for our needs? I agree the current testing pipeline is a bit of a mess since Azure Pipelines necessary permissions don't mesh well with ASF, as described in https://issues.apache.org/jira/browse/INFRA-17030. This has led us to a somewhat makeshift solution (#363). It would be great to simplify things, and if GitHub-hosted runners for actions are viable, I'm +1. If we ever decide to use Azure infrastructure in the future for other types of tests, we can see how to run them on Azure at that time.

@jcamachor it was due to the credits we were able to get on Azure originally. We use GitHub actions internally and were able to run the tests. Where can I find information about the runners we have access to as part of ASF?

**Comment by jcamachor** [comment]
@daragu , yes, we should try. I found this information: https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status Though it does not seem to provide details about the runners.

I found this as well, maybe something to consider if github-hosted runners are not sufficient: https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=ASF+Infra+provided+self-hosted+runners

**Comment by daragu** [comment]
> hi @the-other-tim-brown @jcamachor let's give it a try?

hi @the-other-tim-brown, I would like to hear your opinion.

**Comment by daragu** [comment]
> @daragu , yes, we should try. I found this information: https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status Though it does not seem to provide details about the runners.
> 
> I found this as well, maybe something to consider if github-hosted runners are not sufficient: https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=ASF+Infra+provided+self-hosted+runners

👍

**Comment by the-other-tim-brown** [comment]
@daragu I am in support of this, let's make sure to follow the instructions in that doc. I am also more familiar with GitHub actions and the default runner should work for us based on my experience.

**Comment by daragu** [comment]
> @daragu I am in support of this, let's make sure to follow the instructions in that doc. I am also more familiar with GitHub actions and the default runner should work for us based on my experience.

Glad to hear this news 👍👍👍
