### ISSUE TITLE
Introduce apache rat plugin to xtable project

### ISSUE THREAD

**Issue by daragu** [apache/incubator-xtable#449]
### Feature Request / Improvement

As we known, `apache-rat` plugin cat verify whether source code matches standards like the [ASF Source Header and Copyright Notice Policy](https://www.apache.org/legal/src-headers.html), and this plugin is widely used in many projects, like hudi, flink ...

The `spotless-maven-plugin` can only check several file types, so it can't fits our need.

https://creadur.apache.org/rat/apache-rat-plugin/usage.html

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
Closing the issue as PR is merged.
