### ISSUE TITLE
The github workflow requires approval from a maintainer

### ISSUE THREAD

**Issue by daragu** [apache/incubator-xtable#490]
### Feature Request / Improvement

The github workflow requires approval from a maintainer, but this issue does not exist in other apache projects, can we solve it?

![图片](https://github.com/apache/incubator-xtable/assets/168054694/ebde03d4-01b3-4b17-b5a3-06b3138d0767)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daragu** [comment]
cc @jcamachor @the-other-tim-brown

**Comment by jcamachor** [comment]
Thanks, @daragu . I have created a ticket with ASF INFRA to address this: https://issues.apache.org/jira/browse/INFRA-25953

**Comment by daragu** [comment]
> Thanks, @daragu . I have created a ticket with ASF INFRA to address this: https://issues.apache.org/jira/browse/INFRA-25953

👍

**Comment by daragu** [comment]
The setting has been updated for the inbucator-xtable repository
