### ISSUE TITLE
`Too many files with unapproved license` Error running mvn clean package on `main`

### ISSUE THREAD

**Issue by eastlondoner** [apache/incubator-xtable#496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

I checked out main and used docker-used maven (https://hub.docker.com/_/maven) to run `mvn clean package` but it fails with this error: 

```
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.16.1:check (default) on project xtable: Too many files with unapproved license: 624 See RAT report in: /usr/src/mymaven/target/rat.txt -> [Help 1]
```

To reproduce:
```
git checkout main
docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.8-openjdk-11-slim mvn clean package
```

The last part of the build output is:
```
 Reactor Summary for xtable 0.1.0-SNAPSHOT:
[INFO] 
[INFO] xtable ............................................. FAILURE [ 12.005 s]
[INFO] xtable-api ......................................... SKIPPED
[INFO] xtable-hudi-support ................................ SKIPPED
[INFO] xtable-hudi-support-utils .......................... SKIPPED
[INFO] xtable-core ........................................ SKIPPED
[INFO] xtable-utilities ................................... SKIPPED
[INFO] xtable-hudi-support-extensions ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.151 s
[INFO] Finished at: 2024-07-26T11:24:53Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.16.1:check (default) on project xtable: Too many files with unapproved license: 624 See RAT report in: /usr/src/mymaven/target/rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Are you willing to submit PR?

- [X] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eastlondoner** [comment]
adding `-Drat.skip` seems to fix it, but this isn't included in the README as far as I can tell

**Comment by vinishjail97** [comment]
Are you sure you don't have any local/uncommitted files without the apache header when running `mvn install -DskipTests` ?

**Comment by eastlondoner** [comment]
Ah! You’re right, sorry.I have my environment set up so that the m2 cache is separate for each repo and written to a .m2 directory. The files it was complaining about are all in there.Sent from my iPhoneOn 1 Aug 2024, at 14:50, Vinish Reddy ***@***.***> wrote:﻿
Are you sure you don't have any local/uncommitted files without the apache header when running mvn install -DskipTests ?

**Comment by vinishjail97** [comment]
Closing this, no longer an issue.
