### ISSUE TITLE
Incorrect product name and distribution years in NOTICE file inside jars

### ISSUE THREAD

**Issue by zabetak** [apache/incubator-xtable#509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

```
mvn clean package -DskipTests
jar xf ./xtable-core/target/xtable-core-0.1.0-SNAPSHOT.jar META-INF/NOTICE
cat META-INF/NOTICE
```
Currently the NOTICE file contains the following:
```
xtable-core
Copyright 2023 The Apache Software Foundation
```

The distribution years must reflect the current year (i.e., 2024) and instead of having the module name it may be preferred to use the product name (with the incubation mention) in the NOTICE file.

```
Apache XTable (incubating)
Copyright 2024 The Apache Software Foundation
```

### Are you willing to submit PR?

- [X] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
I have looked at the NOTICE files after pulling the latest main branch containing https://github.com/apache/incubator-xtable/pull/510 

The file does reflects the correct date now.
```
xtable-core
Copyright 2024 The Apache Software Foundation

```

**Comment by vinishjail97** [comment]
Pushed a PR for changing the module names in pom.xml to reflect the apache compliant name in NOTICE. Can you review if this version of the NOTICE file is okay ? 
https://github.com/apache/incubator-xtable/pull/511 

```
Apache XTable (incubating) Core
Copyright 2024 The Apache Software Foundation


This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).

```
