### ISSUE TITLE
xtable has scala jar dependencies - should you suffix your jar names with the scala version?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-xtable#529]
### Feature Request / Improvement

I'm an IPMC member looking at your probably invalid 0.1.0 release.
I noticed in your xtable-core pom that you have a dependency on jackson-module-scala_2.12 - what if you want to support Scala 2.13? The Scala norm is that you should release a jar called xtable-core_2.12 and then possibly also an xtable-core_2.13 jar.

https://repository.apache.org/content/groups/staging/org/apache/xtable/xtable-core/0.1.0-incubating/xtable-core-0.1.0-incubating.pom

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
That can happen because of Spark and Scala version compatibility, can you share what were you trying to do ?

**Comment by pjfanning** [comment]
* we can raise an issue with Apache Hudi to publish the missing jar
* it doesn't stop XTable team from getting a Scala 2.12 build together that published xtable jars with the _2.12 suffix (Scala style for jar names)
* this would get us to a good position to later support Scala 2.13 and eventually Scala 3

**Comment by pjfanning** [comment]
Apache Hudi open issues for Scala 2.13

https://github.com/apache/hudi/issues?q=is%3Aissue+is%3Aopen+scala+2.13
