### ISSUE TITLE
xtable-core pom has a hardcoded scala version for jackson-module-scala

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-xtable#530]
### Feature Request / Improvement

https://repository.apache.org/content/groups/staging/org/apache/xtable/xtable-core/0.1.0-incubating/xtable-core-0.1.0-incubating.pom

scala.version.prefix is used for other jars but you have jackson-module-scala_2.12 as an explicit dependency.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rangareddy** [comment]
Hi @pjfanning 

I will work on this issue

**Comment by rangareddy** [comment]
Raised pull request [537](https://github.com/apache/incubator-xtable/pull/537)
