### ISSUE TITLE
xtable poms are missing license details

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-xtable#531]
### Feature Request / Improvement

License is not defined in 
* https://repository.apache.org/content/groups/staging/org/apache/xtable/xtable/0.1.0-incubating/xtable-0.1.0-incubating.pom
* https://repository.apache.org/content/groups/staging/org/apache/xtable/xtable-core/0.1.0-incubating/xtable-core-0.1.0-incubating.pom 

https://repo1.maven.org/maven2/org/apache/pekko/pekko-actor_3/1.1.0/pekko-actor_3-1.1.0.pom shows how license can be declared.

```
<licenses>
<license>
<name>Apache-2.0</name>
<url>https://www.apache.org/licenses/LICENSE-2.0.html</url>
<distribution>repo</distribution>
</license>
</licenses>
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rangareddy** [comment]
Hi @pjfanning

I will work on this jira.

**Comment by rangareddy** [comment]
**Created a pull request:**

https://github.com/apache/incubator-xtable/pull/533
