### ISSUE TITLE
add DISCLAIMER to META-INF in jars

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-xtable#532]
### Feature Request / Improvement

You add LICENSE and NOTICE to the META-INF in your jars but many Incubator projects also put their DISCLAIMER in the jar.
I'm not 100% sure this is required but it may be a norm.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
@rangareddy will be working on this.
