### ISSUE TITLE
Remove public preview info on SF Iceberg support

### ISSUE THREAD

**Issue by sagarlakshmipathy** [apache/incubator-xtable#579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

Remove public preview info on SF Iceberg support as Iceberg support on SF is GA 

### Are you willing to submit PR?

- [X] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
Closing this as PR is merged.
