### ISSUE TITLE
Delta table delete rows tests incorrectly uses merge operation

### ISSUE THREAD

**Issue by ashvina** [apache/incubator-xtable#588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

The current implementation of the delete rows method for Delta tables, `TestSparkDeltaTable.deleteRows` does not actually delete the table rows. Instead, it performs a merge-with-delete operation. This is incorrect behavior as the table history does not produce a delete operation or delete vectors if enabled. Below is the table history (showing operation and operation properties) of the test delta table in the `ITDeltaConversionTargetSource` test:

> MERGE :: Map(..., matchedPredicates -> [{"actionType":"delete"}], notMatchedPredicates -> [], notMatchedBySourcePredicates -> [])
> MERGE :: Map(..., matchedPredicates -> [{"actionType":"update"}], notMatchedPredicates -> [], notMatchedBySourcePredicates -> [])

### Are you willing to submit PR?

- [X] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
Thanks for reporting the issue, added comments on the PR.
