### ISSUE TITLE
Simplify SourceClient inerface by replacing getSchemaCatalog with getSchema

### ISSUE THREAD

**Issue by ashvina** [apache/incubator-xtable#77]
Each commit is linked to a single schema. As such returning a `SchemaCatalog` (encapsulates a map of schema version and schema) is confusing. The API could be simplified and the `SchemaCatalog` could be removed if it has limited functionality.

_Originally posted by @ashvina in https://github.com/onetable-io/onetable/pull/75#discussion_r1358705374_

**Comment by coded9** [comment]
@ashvina could you assign to me?

**Comment by ashvina** [comment]
@coded9, thanks for offering to fix this. I have assigned it to you, please create a PR.

**Comment by coded9** [comment]
@ashvina could you review #294

**Comment by gzagarwal** [comment]
@ashvina is this completed ? i think pr merge is pending according to the review , apologise if i missed anything

**Comment by the-other-tim-brown** [comment]
@gzagarwal this is not yet completed since the PR is not yet approved and has feedback that needs to be addressed. @coded9 will you be working on this?

**Comment by coded9** [comment]
@the-other-tim-brown I will get back to you with the changes this week

**Comment by the-other-tim-brown** [comment]
Assigning this to myself due to lack of activity. I am just removing the schema catalog for now. We can add a `getSchema` API once there is a use for one. I want to keep the interfaces lean for our first release to minimize any future breaking changes.

**Comment by coded9** [comment]
Hey @the-other-tim-brown I am extremely sorry about the inactivity. I just got freed and available to make the necessary changes
